<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\LedgerFlow.Infrastructure\LedgerFlow.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\LedgerFlow.Migrations.SqlServer\LedgerFlow.Migrations.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>

</Project>
